module.exports.up = function up(db, { ensureColumn, ensureIndex }) {
  const columnBackfills = [
    ['users', 'avatar_url', 'avatar_url TEXT'],
    ['users', 'username', 'username TEXT'],
    ['users', 'gitea_username', 'gitea_username TEXT'],
    ['users', 'gitea_synced_at', 'gitea_synced_at TEXT'],
    ['projects', 'team_id', 'team_id INTEGER'],
    ['projects', 'created_by', 'created_by INTEGER'],
    ['projects', 'legacy_key', 'legacy_key TEXT'],
    ['projects', 'gitea_repo_url', 'gitea_repo_url TEXT'],
    ['submissions', 'submitted_by', 'submitted_by INTEGER'],
    ['submissions', 'details', 'details TEXT'],
    ['project_milestones', 'parent_id', 'parent_id INTEGER'],
    ['project_milestones', 'sort_order', 'sort_order INTEGER'],
    ['project_milestones', 'assignee', 'assignee TEXT'],
    ['project_milestones', 'start_date', 'start_date TEXT'],
    ['project_milestones', 'end_date', 'end_date TEXT'],
    ['project_milestones', 'source', 'source TEXT'],
    ['project_milestones', 'source_key', 'source_key TEXT'],
    ['assessment_files', 'title', 'title TEXT'],
    ['assessment_files', 'uploaded_by', 'uploaded_by INTEGER'],
    ['assignments', 'lesson_id', 'lesson_id TEXT'],
    ['assignments', 'rubric', 'rubric TEXT'],
    ['assignment_submissions', 'link', 'link TEXT'],
    ['assignment_submissions', 'attachment_note', 'attachment_note TEXT'],
    ['competition_registrations', 'teacher_feedback', 'teacher_feedback TEXT'],
    ['competition_reminders', 'target_group', 'target_group TEXT'],
    ['competition_reminders', 'read_at', 'read_at TEXT'],
    ['student_profiles', 'school_stage', 'school_stage TEXT'],
    ['student_profiles', 'grade_level', 'grade_level TEXT'],
    ['student_profiles', 'class_name', 'class_name TEXT'],
    ['student_profiles', 'interest_tags', 'interest_tags TEXT'],
    ['student_profiles', 'skill_tags', 'skill_tags TEXT'],
    ['student_profiles', 'target_tags', 'target_tags TEXT'],
    ['student_profiles', 'weekly_hours', 'weekly_hours INTEGER'],
    ['student_profiles', 'experience_level', 'experience_level TEXT'],
    ['student_profiles', 'preferred_team_size', 'preferred_team_size TEXT'],
    ['student_profiles', 'device_access', 'device_access TEXT'],
    ['student_profiles', 'notes', 'notes TEXT'],
    ['student_profiles', 'profile_version', 'profile_version INTEGER NOT NULL DEFAULT 1'],
    ['match_results', 'rule_breakdown', 'rule_breakdown TEXT'],
    ['match_results', 'reasons', 'reasons TEXT'],
    ['match_results', 'gaps', 'gaps TEXT'],
    ['match_results', 'ai_summary', 'ai_summary TEXT'],
    ['match_results', 'ai_advice', 'ai_advice TEXT'],
    ['match_results', 'rule_version', 'rule_version TEXT'],
    ['match_results', 'ai_version', 'ai_version TEXT'],
    ['match_results', 'source_snapshot', 'source_snapshot TEXT'],
    ['match_results', 'expires_at', 'expires_at TEXT'],
    ['match_reminders', 'candidate_bucket', 'candidate_bucket TEXT'],
    ['match_reminders', 'read_at', 'read_at TEXT'],
    ['project_topics', 'tags', 'tags TEXT'],
    ['project_topics', 'required_skills', 'required_skills TEXT'],
    ['project_topics', 'estimated_hours', 'estimated_hours INTEGER'],
    ['project_topics', 'related_course_id', 'related_course_id TEXT'],
    ['project_topics', 'related_competition_slug', 'related_competition_slug TEXT'],
    ['knowledge_responses', 'user_id', 'user_id INTEGER'],
    ['knowledge_responses', 'episode_key', 'episode_key TEXT'],
    ['knowledge_responses', 'episode_index', 'episode_index INTEGER'],
    ['knowledge_responses', 'focus', 'focus TEXT'],
    ['knowledge_responses', 'summary', 'summary TEXT'],
    ['knowledge_responses', 'ai_score', 'ai_score REAL'],
    ['knowledge_responses', 'ai_feedback', 'ai_feedback TEXT'],
    ['knowledge_responses', 'ai_rubric', 'ai_rubric TEXT'],
    ['knowledge_responses', 'score_provider', 'score_provider TEXT'],
    ['knowledge_responses', 'learner_token', 'learner_token TEXT'],
    ['knowledge_responses', 'viewer_token', 'viewer_token TEXT'],
    ['knowledge_responses', 'passed', 'passed INTEGER NOT NULL DEFAULT 0'],
    ['knowledge_responses', 'share_publicly', 'share_publicly INTEGER NOT NULL DEFAULT 1'],
    ['knowledge_responses', 'updated_at', 'updated_at TEXT'],
    ['knowledge_open_prompts', 'prompt_type', 'prompt_type TEXT'],
    ['knowledge_open_prompts', 'options_json', 'options_json TEXT'],
    ['knowledge_open_prompts', 'correct_answer', 'correct_answer TEXT']
  ];

  columnBackfills.forEach(([tableName, columnName, columnDef]) => {
    ensureColumn(db, tableName, columnName, columnDef);
  });
  ensureIndex(db, 'idx_users_username_unique', 'users', 'username', "WHERE username IS NOT NULL AND username != ''");
};
